language: generic
sudo: false
before_install:
  - apt-get -qq update
  - apt-get install -y silversearcher-ag
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
script:
  - emacs --version
  - make test
